### ISSUE TITLE
有方法能控制成动画的执行么？

### ISSUE THREAD

**Issue by callmesoul** [OYsun/VueStar#2]
现在有这么个需求，用户点赞后不可以再点赞，也不可以取消。怎么实现？

**Comment by OYsun** [comment]
@callmesoul 我的想法是这个点赞组件只提供一个基础的点赞动画切换逻辑，至于其它复杂的逻辑都可以绑定在`slot`中，比如你说的“用户点赞后不可以再点赞，也不可以取消”，你可以在`slot`绑定一个事件，逻辑是当用户点赞后，禁用`slot`中的内容，使它不可点击等等。
